package Ventanas;
import Archivos.GestorArchivo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class FloraVentana extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelos = new DefaultTableModel();

    /**
     * Creates new form FloraVentana
     */
    public FloraVentana() {
        initComponents();
        setLocationRelativeTo(null);
        modelo.addColumn("Nombre Flora");
        modelos.addColumn("Tipo de Flora");

        GestorArchivo a = new GestorArchivo();
        String ruta = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Flora\\Flora\\";

        String[] lista = a.leerArchivo(ruta).split("\n");

        for (int i = 0; i < lista.length; i++) {
            lista[0] = lista[i];

            modelo.addRow(lista);// a nuestro modelo le agregamos nuestro objeto fila
            TablaFlora.setModel(modelo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFlora = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtNumeros = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladetalles = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 460));
        getContentPane().setLayout(null);

        TablaFlora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaFlora);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 20, 360, 110);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 150, 100, 23);
        getContentPane().add(txtNumeros);
        txtNumeros.setBounds(170, 150, 115, 20);

        tabladetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabladetalles);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 200, 370, 120);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 150, 100, 23);

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 340, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modelos.setRowCount(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GestorArchivo b = new GestorArchivo();

        String rutas = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Flora\\Flora\\";
        String[] datos = b.leerArchivo(rutas).split("\n");

        String numero = txtNumeros.getText();
        int Numero = Integer.parseInt(numero);
        ;
        if (Numero < 1||Numero>28) {
         JOptionPane.showMessageDialog(null, "El numero ingresado no es correcto, ingrese un numero nuevamente");
         } else {
        if (Numero == 1) {
            Numero = Numero - 1;
            datos[0] = datos[Numero];

            modelos.addRow(datos);
            tabladetalles.setModel(modelos);
        } else {
        }
        if (Numero == 2) {
            Numero = Numero - 1;
            datos[0] = datos[Numero];

            modelos.addRow(datos);
            tabladetalles.setModel(modelos);
        } else {
        }
        if (Numero == 3) {
            Numero = Numero - 1;
            datos[0] = datos[Numero];

            modelos.addRow(datos);
            tabladetalles.setModel(modelos);
        } else {
        }
        if (Numero == 4) {
            Numero = Numero - 1;
            datos[0] = datos[Numero];

            modelos.addRow(datos);
            tabladetalles.setModel(modelos);
        } else {
        }
        if (Numero == 5) {
            Numero = Numero - 1;
            datos[0] = datos[Numero];

            modelos.addRow(datos);
            tabladetalles.setModel(modelos);
        } else {
        }
        if (Numero == 6) {
            Numero = Numero - 1;
            datos[0] = datos[Numero];

            modelos.addRow(datos);
            tabladetalles.setModel(modelos);
        } else {
        }
        if (Numero == 7) {
            Numero = Numero - 1;
            datos[0] = datos[Numero];

            modelos.addRow(datos);
            tabladetalles.setModel(modelos);
        } else {
            if (Numero == 8) {
                Numero = Numero - 1;
                datos[0] = datos[Numero];

                modelos.addRow(datos);
                tabladetalles.setModel(modelos);
            } else {
                if (Numero == 9) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 10) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 11) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 12) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 13) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 14) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 15) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 16) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 17) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 18) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 19) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 20) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 21) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 22) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 23) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 24) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 25) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 26) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 27) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 28) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
            }
            txtNumeros.setText("");
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TurismoAraucania.Controlador_Flora.BotonSalir();
        modelos.setRowCount(0);
      
       txtNumeros.setText("");
       
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FloraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FloraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FloraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FloraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FloraVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFlora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabladetalles;
    private javax.swing.JTextField txtNumeros;
    // End of variables declaration//GEN-END:variables
}
