/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Archivos.GestorArchivo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class VentanaAnimal extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelos = new DefaultTableModel();

    /**
     * Creates new form VentanaAnimal
     */
    public VentanaAnimal() {
        initComponents();
        setLocationRelativeTo(null);
        modelos.addColumn("Datos del animal");
        modelo.addColumn("Nombre del animal");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAnimales = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladetalles = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNumeros = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaInformacion = new javax.swing.JTable();
        TextoAnimales = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(780, 570));
        getContentPane().setLayout(null);

        TablaAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaAnimales.setMinimumSize(new java.awt.Dimension(700, 500));
        jScrollPane1.setViewportView(TablaAnimales);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(346, 91, 375, 140);

        tabladetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabladetalles);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(90, 360, 530, 120);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 320, 110, 23);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 490, 100, 23);
        getContentPane().add(txtNumeros);
        txtNumeros.setBounds(260, 320, 115, 20);

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 510, 120, 23);

        jButton4.setText("CargarAnimales");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(560, 60, 150, 23);

        TablaInformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Anfibios"},
                {"Aves"},
                {"Insectos"},
                {"Mamiferos"},
                {"Peces"},
                {"Reptiles"},
                {null}
            },
            new String [] {
                "Animales"
            }
        ));
        jScrollPane3.setViewportView(TablaInformacion);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 90, 318, 140);

        TextoAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoAnimalesActionPerformed(evt);
            }
        });
        getContentPane().add(TextoAnimales);
        TextoAnimales.setBounds(400, 60, 120, 20);

        jButton5.setText("Limpiar Tabla");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(490, 240, 160, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String txt = TextoAnimales.getText();
        if (txt.equals("Anfibios")) {
            GestorArchivo b = new GestorArchivo();

            String rutas = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Anfibios\\Datos";
            String[] datos = b.leerArchivo(rutas).split("\n");

            String numero = txtNumeros.getText();
            int Numero = Integer.parseInt(numero);
            ;
            if (Numero < 1 || Numero > 6) {
                JOptionPane.showMessageDialog(null, "El numero ingresado no es correcto, ingrese un numero nuevamente");
            } else {
                if (Numero == 1) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 2) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 3) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 4) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 5) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                }
                if (Numero == 6) {
                    Numero = Numero - 1;
                    datos[0] = datos[Numero];

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                }
            }

            txtNumeros.setText("");

        } else {
            if (txt.equals("Aves")) {
                GestorArchivo b = new GestorArchivo();

                String rutas = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Aves\\Datos";
                String[] datos = b.leerArchivo(rutas).split("\n");

                String numero = txtNumeros.getText();
                int Numero = Integer.parseInt(numero);
                ;
                if (Numero < 1 || Numero > 8) {
                    JOptionPane.showMessageDialog(null, "El numero ingresado no es correcto, ingrese un numero nuevamente");
                } else {
                    if (Numero == 1) {
                        Numero = Numero - 1;
                        datos[0] = datos[Numero];

                        modelos.addRow(datos);
                        tabladetalles.setModel(modelos);
                    } else {
                    }
                    if (Numero == 2) {
                        Numero = Numero - 1;
                        datos[0] = datos[Numero];

                        modelos.addRow(datos);
                        tabladetalles.setModel(modelos);
                    } else {
                    }
                    if (Numero == 3) {
                        Numero = Numero - 1;
                        datos[0] = datos[Numero];

                        modelos.addRow(datos);
                        tabladetalles.setModel(modelos);
                    } else {
                    }
                    if (Numero == 4) {
                        Numero = Numero - 1;
                        datos[0] = datos[Numero];

                        modelos.addRow(datos);
                        tabladetalles.setModel(modelos);
                    } else {
                    }
                    if (Numero == 5) {
                        Numero = Numero - 1;
                        datos[0] = datos[Numero];

                        modelos.addRow(datos);
                        tabladetalles.setModel(modelos);
                    } else {
                    }
                    if (Numero == 6) {
                        Numero = Numero - 1;
                        datos[0] = datos[Numero];

                        modelos.addRow(datos);
                        tabladetalles.setModel(modelos);
                    } else {
                    }
                    if (Numero == 7) {
                        Numero = Numero - 1;
                        datos[0] = datos[Numero];

                        modelos.addRow(datos);
                        tabladetalles.setModel(modelos);
                    } else {
                    }
                    if (Numero == 8) {
                        Numero = Numero - 1;
                        datos[0] = datos[Numero];

                        modelos.addRow(datos);
                        tabladetalles.setModel(modelos);
                    }

                }

                txtNumeros.setText("");

            } else {
                if (txt.equals("Insectos")) {
                    GestorArchivo b = new GestorArchivo();

                    String rutas = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Insectos\\Datos";
                    String[] datos = b.leerArchivo(rutas).split("\n");

                    String numero = txtNumeros.getText();
                    int Numero = Integer.parseInt(numero);
                    ;
                    if (Numero < 1 || Numero > 7) {
                        JOptionPane.showMessageDialog(null, "El numero ingresado no es correcto, ingrese un numero nuevamente");
                    } else {
                        if (Numero == 1) {
                            Numero = Numero - 1;
                            datos[0] = datos[Numero];

                            modelos.addRow(datos);
                            tabladetalles.setModel(modelos);
                        } else {
                        }
                        if (Numero == 2) {
                            Numero = Numero - 1;
                            datos[0] = datos[Numero];

                            modelos.addRow(datos);
                            tabladetalles.setModel(modelos);
                        } else {
                        }
                        if (Numero == 3) {
                            Numero = Numero - 1;
                            datos[0] = datos[Numero];

                            modelos.addRow(datos);
                            tabladetalles.setModel(modelos);
                        } else {
                        }
                        if (Numero == 4) {
                            Numero = Numero - 1;
                            datos[0] = datos[Numero];

                            modelos.addRow(datos);
                            tabladetalles.setModel(modelos);
                        } else {
                        }
                        if (Numero == 5) {
                            Numero = Numero - 1;
                            datos[0] = datos[Numero];

                            modelos.addRow(datos);
                            tabladetalles.setModel(modelos);
                        } else {
                        }
                        if (Numero == 6) {
                            Numero = Numero - 1;
                            datos[0] = datos[Numero];

                            modelos.addRow(datos);
                            tabladetalles.setModel(modelos);
                        } else {
                        }
                        if (Numero == 7) {
                            Numero = Numero - 1;
                            datos[0] = datos[Numero];

                            modelos.addRow(datos);
                            tabladetalles.setModel(modelos);
                        }

                    }

                    txtNumeros.setText("");

                } else {
                    if (txt.equals("Mamiferos")) {
                        GestorArchivo b = new GestorArchivo();

                        String rutas = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Mamiferos\\Datos";
                        String[] datos = b.leerArchivo(rutas).split("\n");

                        String numero = txtNumeros.getText();
                        int Numero = Integer.parseInt(numero);
                        ;
                        if (Numero < 1 || Numero > 11) {
                            JOptionPane.showMessageDialog(null, "El numero ingresado no es correcto, ingrese un numero nuevamente");
                        } else {
                            if (Numero == 1) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            } else {
                            }
                            if (Numero == 2) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            } else {
                            }
                            if (Numero == 3) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            } else {
                            }
                            if (Numero == 4) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            } else {
                            }
                            if (Numero == 5) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            } else {
                            }
                            if (Numero == 6) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            } else {
                            }
                            if (Numero == 7) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            } else {
                            }
                            if (Numero == 8) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            } else {
                            }
                            if (Numero == 9) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            } else {
                            }
                            if (Numero == 10) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            } else {
                            }
                            if (Numero == 11) {
                                Numero = Numero - 1;
                                datos[0] = datos[Numero];

                                modelos.addRow(datos);
                                tabladetalles.setModel(modelos);
                            }

                        }

                        txtNumeros.setText("");

                    } else {
                        if (txt.equals("Peces")) {
                            GestorArchivo b = new GestorArchivo();

                            String rutas = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Peces\\Datos";
                            String[] datos = b.leerArchivo(rutas).split("\n");

                            String numero = txtNumeros.getText();
                            int Numero = Integer.parseInt(numero);
                            ;
                            if (Numero < 1 || Numero > 6) {
                                JOptionPane.showMessageDialog(null, "El numero ingresado no es correcto, ingrese un numero nuevamente");
                            } else {
                                if (Numero == 1) {
                                    Numero = Numero - 1;
                                    datos[0] = datos[Numero];

                                    modelos.addRow(datos);
                                    tabladetalles.setModel(modelos);
                                } else {
                                }
                                if (Numero == 2) {
                                    Numero = Numero - 1;
                                    datos[0] = datos[Numero];

                                    modelos.addRow(datos);
                                    tabladetalles.setModel(modelos);
                                } else {
                                }
                                if (Numero == 3) {
                                    Numero = Numero - 1;
                                    datos[0] = datos[Numero];

                                    modelos.addRow(datos);
                                    tabladetalles.setModel(modelos);
                                } else {
                                }
                                if (Numero == 4) {
                                    Numero = Numero - 1;
                                    datos[0] = datos[Numero];

                                    modelos.addRow(datos);
                                    tabladetalles.setModel(modelos);
                                } else {
                                }
                                if (Numero == 5) {
                                    Numero = Numero - 1;
                                    datos[0] = datos[Numero];

                                    modelos.addRow(datos);
                                    tabladetalles.setModel(modelos);
                                } else {
                                }
                                if (Numero == 6) {
                                    Numero = Numero - 1;
                                    datos[0] = datos[Numero];

                                    modelos.addRow(datos);
                                    tabladetalles.setModel(modelos);
                                }
                            }

                            txtNumeros.setText("");

                        } else {
                            if (txt.equals("Reptiles")) {
                                GestorArchivo b = new GestorArchivo();

                                String rutas = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Reptiles\\Datos";
                                String[] datos = b.leerArchivo(rutas).split("\n");

                                String numero = txtNumeros.getText();
                                int Numero = Integer.parseInt(numero);
                                ;
                                if (Numero < 1 || Numero > 5) {
                                    JOptionPane.showMessageDialog(null, "El numero ingresado no es correcto, ingrese un numero nuevamente");
                                } else {
                                    if (Numero == 1) {
                                        Numero = Numero - 1;
                                        datos[0] = datos[Numero];

                                        modelos.addRow(datos);
                                        tabladetalles.setModel(modelos);
                                    } else {
                                    }
                                    if (Numero == 2) {
                                        Numero = Numero - 1;
                                        datos[0] = datos[Numero];

                                        modelos.addRow(datos);
                                        tabladetalles.setModel(modelos);
                                    } else {
                                    }
                                    if (Numero == 3) {
                                        Numero = Numero - 1;
                                        datos[0] = datos[Numero];

                                        modelos.addRow(datos);
                                        tabladetalles.setModel(modelos);
                                    } else {
                                    }
                                    if (Numero == 4) {
                                        Numero = Numero - 1;
                                        datos[0] = datos[Numero];

                                        modelos.addRow(datos);
                                        tabladetalles.setModel(modelos);
                                    } else {
                                    }
                                    if (Numero == 5) {
                                        Numero = Numero - 1;
                                        datos[0] = datos[Numero];

                                        modelos.addRow(datos);
                                        tabladetalles.setModel(modelos);
                                    }
                                }

                                txtNumeros.setText("");

                            } else {

                            }
                        }
                    }

                }

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TurismoAraucania.Controlador_Animales.BotonSalir();
        modelo.setRowCount(0);
        modelos.setRowCount(0);
        txtNumeros.setText("");
        TextoAnimales.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String txt = TextoAnimales.getText();
        if (txt.equals("Anfibios")) {
            GestorArchivo a = new GestorArchivo();
            String ruta = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Anfibios\\Nombres";

            String[] lista = a.leerArchivo(ruta).split("\n");

            for (int i = 0; i < lista.length; i++) {
                lista[0] = lista[i];

                modelo.addRow(lista);// a nuestro modelo le agregamos nuestro objeto fila
                TablaAnimales.setModel(modelo);

            }
        } else {
            if (txt.equals("Aves")) {
                GestorArchivo a = new GestorArchivo();
                String ruta = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Aves\\Nombres";

                String[] lista = a.leerArchivo(ruta).split("\n");

                for (int i = 0; i < lista.length; i++) {
                    lista[0] = lista[i];

                    modelo.addRow(lista);// a nuestro modelo le agregamos nuestro objeto fila
                    TablaAnimales.setModel(modelo);

                }
            } else {
                if (txt.equals("Insectos")) {
                    GestorArchivo a = new GestorArchivo();
                    String ruta = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Insectos\\Nombres";

                    String[] lista = a.leerArchivo(ruta).split("\n");

                    for (int i = 0; i < lista.length; i++) {
                        lista[0] = lista[i];

                        modelo.addRow(lista);// a nuestro modelo le agregamos nuestro objeto fila
                        TablaAnimales.setModel(modelo);

                    }
                } else {
                    if (txt.equals("Mamiferos")) {
                        GestorArchivo a = new GestorArchivo();
                        String ruta = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Mamiferos\\Nombres";

                        String[] lista = a.leerArchivo(ruta).split("\n");

                        for (int i = 0; i < lista.length; i++) {
                            lista[0] = lista[i];

                            modelo.addRow(lista);// a nuestro modelo le agregamos nuestro objeto fila
                            TablaAnimales.setModel(modelo);

                        }
                    } else {
                        if (txt.equals("Peces")) {
                            GestorArchivo a = new GestorArchivo();
                            String ruta = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Peces\\Nombres";

                            String[] lista = a.leerArchivo(ruta).split("\n");

                            for (int i = 0; i < lista.length; i++) {
                                lista[0] = lista[i];

                                modelo.addRow(lista);// a nuestro modelo le agregamos nuestro objeto fila
                                TablaAnimales.setModel(modelo);

                            }
                        } else {
                            if (txt.equals("Reptiles")) {
                                GestorArchivo a = new GestorArchivo();
                                String ruta = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Animales\\Reptiles\\Nombres";

                                String[] lista = a.leerArchivo(ruta).split("\n");

                                for (int i = 0; i < lista.length; i++) {
                                    lista[0] = lista[i];

                                    modelo.addRow(lista);// a nuestro modelo le agregamos nuestro objeto fila
                                    TablaAnimales.setModel(modelo);

                                }
                            } else {

                                if (TextoAnimales.getText().isEmpty()) {

                                } else {
                                    JOptionPane.showMessageDialog(this, "Ingrese el nombre del animal correcto", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);

                                }
                            }

                        }

                    }

                }

            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void TextoAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoAnimalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoAnimalesActionPerformed
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        modelo.setRowCount(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modelos.setRowCount(0);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaAnimales;
    private javax.swing.JTable TablaInformacion;
    private javax.swing.JTextField TextoAnimales;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabladetalles;
    private javax.swing.JTextField txtNumeros;
    // End of variables declaration//GEN-END:variables
}
