/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Archivos.GestorArchivo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class VentanaLugares extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelos = new DefaultTableModel();

    /**
     * Creates new form VentanaLugares
     */
    public VentanaLugares() {

        initComponents();
        setLocationRelativeTo(null);
        modelo.addColumn("Nombre Lugar");
        modelos.addColumn("Ubicacion");
     
        GestorArchivo a = new GestorArchivo();
        String ruta = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Lugares\\Lugares\\";

        String[] lista = a.leerArchivo(ruta).split("\n");

        for (int i = 0; i < lista.length; i++) {
            lista[0] = lista[i];

            modelo.addRow(lista);// a nuestro modelo le agregamos nuestro objeto fila
            TablaLugares.setModel(modelo);
            //String[] listaNombre = listanombres();
            //for (int i=0; i<listaNombre.length; i++){
            //System.out.println("["+(i)+"]" + " " + listaNombre[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLugares = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladetalles = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 480));
        getContentPane().setLayout(null);

        TablaLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaLugares);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(27, 33, 452, 87);

        tabladetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabladetalles);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(41, 277, 415, 95);

        jButton1.setText("Limpiar Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 180, 130, 23);

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 180, 100, 23);

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumero);
        txtNumero.setBounds(210, 180, 150, 20);

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(347, 403, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        modelos.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GestorArchivo b = new GestorArchivo();
         
        String rutas = "C:\\Users\\hp\\Documents\\NetBeansProjects\\TurismoArau\\Lugares\\Localización\\";
        String[] datos = b.leerArchivo(rutas).split("\n");
      
        
            String numero = txtNumero.getText();
            int Numero = Integer.parseInt(numero);
            ;

       
           
           if (Numero < 1||Numero>9) {
         JOptionPane.showMessageDialog(null, "El numero ingresado no es correcto, ingrese un numero nuevamente");
         } else {
        if (Numero == 1) {
                Numero=Numero-1;
                datos [0] = datos[Numero]; 

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
    }
        if (Numero == 2) {
                Numero=Numero-1;
                datos [0] = datos[Numero]; 

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
    }
        if (Numero == 3) {
                Numero=Numero-1;
                datos [0] = datos[Numero]; 

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
    }
        if (Numero == 4) {
                 Numero=Numero-1;
                datos [0] = datos[Numero]; 

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
    }
        if (Numero == 5) {
                 Numero=Numero-1;
                datos [0] = datos[Numero]; 

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
    }
        if (Numero == 6) {
                 Numero=Numero-1;
                datos [0] = datos[Numero]; 

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
    }
        if (Numero == 7) {
                 Numero=Numero-1;
                datos [0] = datos[Numero]; 

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
             if (Numero == 8) {
                 Numero=Numero-1;
                datos [0] = datos[Numero]; 

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
                  if (Numero == 9) {
                 Numero=Numero-1;
                datos [0] = datos[Numero]; 

                    modelos.addRow(datos);
                    tabladetalles.setModel(modelos);
                } else {
             }
             }
             txtNumero.setText("");   
        } 
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       TurismoAraucania.Controlador_Lugares.BotonSalir();
       modelos.setRowCount(0);
       txtNumero.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLugares().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaLugares;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabladetalles;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
